"""Initial schema

Revision ID: d8c2dad321f6
Revises: 
Create Date: 2026-03-12 16:55:41.541963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c2dad321f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('ra', sa.String(length=20), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('can_create_events', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ra')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('data_inicio', sa.String(length=10), nullable=True),
    sa.Column('hora_inicio', sa.String(length=5), nullable=True),
    sa.Column('data_fim', sa.String(length=10), nullable=True),
    sa.Column('hora_fim', sa.String(length=5), nullable=True),
    sa.Column('token_publico', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cert_bg_path', sa.String(length=200), nullable=True),
    sa.Column('cert_template_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('palestrante', sa.String(length=100), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_atv', sa.String(length=10), nullable=True),
    sa.Column('hora_atv', sa.String(length=5), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_cpf', sa.String(length=14), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('cert_hash', sa.String(length=64), nullable=True),
    sa.Column('cert_entregue', sa.Boolean(), nullable=True),
    sa.Column('cert_data_envio', sa.DateTime(), nullable=True),
    sa.Column('cert_email_alternativo', sa.String(length=120), nullable=True),
    sa.Column('lat_checkin', sa.Float(), nullable=True),
    sa.Column('lon_checkin', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_cpf'], ['users.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_enrollments')
    op.drop_table('activities')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
